### PR TITLE
fix: don't display testnet rounds in production on expl. homepage

### LINKED ISSUE #2082: Explorer: Remove PGN testnet rounds from Explorer homepage on production (no testnets should be supported)
**Overview**
- https://explorer.gitcoin.co/#/round/58008/0x7530937a7c0f74201d78930d31f738868e5b1465
- https://explorer.gitcoin.co/#/round/58008/0xbe0cbcb187856a183bdb69947cbdb79b0bf4d69d

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

### PR DESCRIPTION
**Pull request by vacekj**
## PR checklist

For every PR, make sure that these statements are true:
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't contain type casts and non-null assertions.
- [x] Doesn't add `@ts-ignore`.
- [x] Doesn't disable lints.
- [x] Doesn't use `useState` just for computation - use plain variables instead.
- [x] Splits components into pure components that don't depend on external state or hooks.
- [x] Avoid embedding components within other components
- [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
- [x] Doesn't duplicate existing code.
- [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
- [x] Doesn't contain commented out code.
- [x] Doesn't contain skipped or empty tests.

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Refers/Fixes

fixes #2082

### CODE REVIEW

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 1]
```diff
@@ -3,19 +3,22 @@ import { RoundMetadata } from "./round";
...
 import { ethers } from "ethers";
+import { allChains } from "../../app/chainConfig";
 
 interface GetRoundOverviewResult {
   data: {
     rounds: RoundOverview[];
   };
 }
 
+/*TODO: what is this */
```
Comment (bard) [inline packages/grant-explorer/src/features/api/rounds.ts:14]: Would be nice to have an explanation here before merging. Who knows about this?

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 2]
```diff
@@ -93,31 +96,29 @@ async function fetchRoundsByTimestamp(
...
 }
 
-function getActiveChainIds() {
-  const activeChainIds: string[] = [];
-  const isProduction = process.env.REACT_APP_ENV === "production";
+/**
+ * Filters out testnet chainIds in production, otherwise returns all active chainIds
+ * */
+const getActiveChainIds = () =>
+  Object.keys(ChainId).filter((chainId) => {
```
Comment (bard) [inline packages/grant-explorer/src/features/api/rounds.ts:103]: I see `allChains` is defined elsewhere as:

```ts
export const allChains: Chain[] =
  process.env.REACT_APP_ENV === "development"
    ? [...testnetChains(), ...mainnetChains()]
    : [...mainnetChains()];
```

So there seems to be a test/non-testnet selection logic already. Does this change need to take that into account?

Unrelated to this PR: would it make sense to try and derive `ChainId` from `allChains` instead of having the id's defined both as enum and as keys in `allChains`? (This reminds me of the Jimmy Koppel's color example about hidden coupling.)

**Review by bard — APPROVED** [review]

File: packages/grant-explorer/src/features/api/rounds.ts (hunk 2 above)
Comment (vacekj) [reply packages/grant-explorer/src/features/api/rounds.ts:103]: true - i didn't realize allChains already has this functionality - this function is therefore superfluous and we can just use the allChains array directly.

second point - it could, but I believe this wouldn't work at comptime, meaning that we would lose the static checking, and ChainId would become just a number, because we don't know the contents of the allChains object at comptime. but maybe `as const` could help here.

Comment (bard) [reply packages/grant-explorer/src/features/api/rounds.ts:103]: Good point. It _might_ become a number union, which _might_ still be ok, but if it became just a `number`, that would be a step back.

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 3]
```diff
@@ -96,32 +96,13 @@ async function fetchRoundsByTimestamp(
...
-    if (
-      process.env.REACT_APP_ENV === "production" &&
-      chainDefinition?.testnet
-    ) {
-      return false;
-    }
-
-    return true;
-  });
+const activeChainIds = allChains
```
Comment (bard) [inline packages/grant-explorer/src/features/api/rounds.ts:99]: I actually liked that you had a function here. If you have two pieces of state, they can get out of sync. If you have one piece of state and one function that derives a value from it, pay a tiny computational price for the reassurance that the value you get is up to date. Not a bad deal.

**Review by bard — APPROVED** [review]

File: packages/grant-explorer/src/features/api/rounds.ts (hunk 1 above)
Comment (boudra) [reply packages/grant-explorer/src/features/api/rounds.ts:14]: @bhargavaparoksham I see you were the one who added it, if I remember correctly this was a temporary measure to fix a production issue, would this be safe to delete now?

Comment (vacekj) [reply packages/grant-explorer/src/features/api/rounds.ts]: All these rounds are old and won't display because the donation period has passed, so afaik it's safe to delete them. i added the names of the rounds to the pr.

**Review by melissa-neira — DISMISSED** [review]

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 4]
```diff
@@ -93,34 +94,12 @@ async function fetchRoundsByTimestamp(
...
-      ].includes(ChainId[chainId as keyof typeof ChainId])
-    ) {
-      continue;
-    }
-    activeChainIds.push(chainId.toString());
-  }
-  return activeChainIds;
-}
+const activeChainIds = () =>
+  allChains.map((chain) => chain.id).map((chainId) => chainId.toString());
```
Comment (boudra) [inline packages/grant-explorer/src/features/api/rounds.ts:98]:
```suggestion
  allChains.map((chain) => chain.id.toString());
```
more concise and less confusing imo

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 5]
```diff
@@ -93,34 +94,12 @@ async function fetchRoundsByTimestamp(
...
-        ChainId.FANTOM_TESTNET_CHAIN_ID,
-      ].includes(ChainId[chainId as keyof typeof ChainId])
-    ) {
-      continue;
-    }
-    activeChainIds.push(chainId.toString());
-  }
-  return activeChainIds;
-}
+const activeChainIds = () =>
```
Comment (bard) [inline packages/grant-explorer/src/features/api/rounds.ts:97]: `getXyz` would make it apparent when seeing at call site that it's a function rather than a value.

**Review by bard — APPROVED** [review]

File: packages/grant-explorer/src/features/api/rounds.ts (hunk 5 above)
Comment (vacekj) [reply packages/grant-explorer/src/features/api/rounds.ts]: Done.

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 6]
```diff
@@ -93,34 +93,16 @@ async function fetchRoundsByTimestamp(
...
-    }
-    activeChainIds.push(chainId.toString());
-  }
-  return activeChainIds;
-}
+const getActiveChainIds = (): ChainId[] =>
+  allChains
+    .map((chain) => chain.id)
+    .map(tryParseChainIdToEnum)
+    .filter((chainId): chainId is ChainId => chainId !== null)
```
Comment (bard) [inline packages/grant-explorer/src/features/api/rounds.ts:100]: `isPresent` from `ts-is-present` might help here (narrowing included)

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 7]
```diff
@@ -65,7 +65,7 @@ async function fetchRoundsByTimestamp(
         round.roundMetaPtr.pointer
       );
       round.roundMetadata = roundMetadata;
-      round.chainId = chainId;
+      round.chainId = chainId.toFixed(0).toString();
```
Comment (bard) [inline packages/grant-explorer/src/features/api/rounds.ts:68]: Two questions pop to mind when seeing this: 1) "is `chainId` a float that it needs a `toFixed`?" and 2) what is the purpose of `toString()` when `toFixed()` returns a string?

File: packages/common/src/chains.ts [hunk 8]
```diff
@@ -17,6 +17,22 @@ export enum ChainId {
   POLYGON_MUMBAI = 80001,
 }
 
+/**
+ * Attempts to parse a numerical or string chainId to the Enum.
+ * returns null if the chainid is invalid */
+export function tryParseChainIdToEnum(chainId: string | number) {
```
Comment (bard) [inline packages/common/src/chains.ts:23]: Declaring the return type of the function would guard against accidentally returning `undefined` or something likewise unintended.

**Review by bard — DISMISSED** [review]

File: packages/grant-explorer/src/features/api/rounds.ts (hunk 7 above)
Comment (vacekj) [reply packages/grant-explorer/src/features/api/rounds.ts:68]: the ToString is indeed superfluous here. this is a workaround for a behaviour of TS enums where if you call toString() on an instance of it, it will output the string value (OPTIMISM_MAINNET) instead of the stringified number ("10"). this is a common gotcha, started a thread in eng. to see how we can improve this.

Comment (vacekj) [reply packages/grant-explorer/src/features/api/rounds.ts:68]: removed the toString

**Review by bard — APPROVED** [review]

File: packages/common/src/chains.ts [hunk 9]
```diff
@@ -17,6 +17,24 @@ export enum ChainId {
...
+ * Attempts to parse a numerical or string chainId to the Enum.
+ * returns null if the chainid is invalid */
+export function tryParseChainIdToEnum(
+  chainId: string | number
+): ChainId | null {
+  const chains = Object.keys(ChainId)
+    .map(Number)
+    .filter((item) => {
+      return !isNaN(item);
+    });
```
Comment (gravityblast) [inline packages/common/src/chains.ts:30]: it would make sense to parse it at runtime if we have runtime values, but I see we use it with `allChains`, can't they be directly the right type so it's done at compile time?

File: packages/grant-explorer/src/features/api/rounds.ts [hunk 10]
```diff
@@ -65,7 +66,7 @@ async function fetchRoundsByTimestamp(
         round.roundMetaPtr.pointer
       );
       round.roundMetadata = roundMetadata;
-      round.chainId = chainId;
+      round.chainId = chainId.toFixed(0);
```
Comment (gravityblast) [inline packages/grant-explorer/src/features/api/rounds.ts:69]: what's the scenario where we need `toFixed` here?

File: packages/common/src/chains.ts (hunk 9 above)
Comment (vacekj) [reply packages/common/src/chains.ts:30]: the id on wagmi's `Chain` type is number. this is not guaranteed to be a chain that we support. that's why we parse it.

File: packages/grant-explorer/src/features/api/rounds.ts (hunk 10 above)
Comment (vacekj) [reply packages/grant-explorer/src/features/api/rounds.ts:69]: image

**Review by gravityblast — APPROVED** [review]
