### PR TITLE
[Bug] Explorer: new bottom nav bar is hiding the Passport banner

### LINKED ISSUE #2191: Explorer: new bottom nav bar is hiding the Passport banner
**Overview**
Context: https://discord.com/channels/562828676480237578/907740735602851840/1141044687210299523 

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

1. New bottom nav bar is hiding the Passport banner in explorer
2. nav bar is overcrowding the thank you page in explorer

##### Refers/Fixes

fixes #2191  #2196

### CODE REVIEW

File: packages/grant-explorer/src/features/common/Navbar.tsx [hunk 1]
```diff
@@ -59,6 +57,12 @@ export default function Navbar(props: NavbarProps) {
             </Link>
           </div>
           <div className="flex items-center gap-6">
+            <RoundsSubNav
+              onClick={(round: NavRound) => {
+                const url = `#/round/${round.chainId}/${round.id}`;
+                window.open(url, "_blank");
```
Comment (bard) [inline packages/grant-explorer/src/features/common/Navbar.tsx:63]: Since we're using an app router:

1. what is the reason to go around it?
2. if it turns out to be a good reason, please add a comment afterwards to explain why the counter-intuitive choice is necessary

**Review by melissa-neira — CHANGES_REQUESTED** [review]
lgtm except in mobile view - the PGN bridge and the GG18 dropdown menu disappear. the rainbowkit component is also a bit too big. can we remove a user's ens/wallet and just keep the little icon instead?

**Review by gravityblast — CHANGES_REQUESTED** [review]
all the alert messages are still hidden now under the subnav, here there's an alert saying `This round has ended. Thank you for your support!` https://bafybeif5bzr6sokrlzbmkzgirrnldvza3nykhk44igxf3epf4bkdwcsfmm.on.fleek.co/#/round/424/0x4473725beb9a9d503547d2fe677f4b5aa39b68f6

**Comment by michellema1208** [comment]
> all the alert messages are still hidden now under the subnav, here there's an alert saying `This round has ended. Thank you for your support!` https://bafybeif5bzr6sokrlzbmkzgirrnldvza3nykhk44igxf3epf4bkdwcsfmm.on.fleek.co/#/round/424/0x4473725beb9a9d503547d2fe677f4b5aa39b68f6

This alert is correct, as the PGN Internal Test Round: Meme Contest ended a few weeks ago!

**Comment by michellema1208** [comment]
@melissa-neira to fix these two issues, I see that @bhargavaparoksham has collapsed the PGN Bridge/GG18 menu into the toplevel nav bar, as opposed to the two nav bars we had designed. I think this makes sense given that we have the Passport banner still - wdyt? 

@bhargavaparoksham if Melissa is OK with your changes, then I'll approve as well (basically, it solves the issue, but is not what we had originally designed)

File: packages/grant-explorer/src/features/common/Navbar.tsx (hunk 1 above)
Comment (bhargavaparoksham) [reply packages/grant-explorer/src/features/common/Navbar.tsx]: Changed it back now as per product suggestion of not opening the round in new tab.

**Review by melissa-neira — APPROVED** [review]

**Review by michellema1208 — APPROVED** [review]
