### PR TITLE
feat(round-settings): fix visual bugs

### LINKED ISSUE #1915: Manager: UX changes for Round Edit flow
### 6/20/23 Update: Backlogged from Round Edit Flow milestone

**Overview**

Some remaining UX work to do on the Round Settings page (when in edit mode): 

**All**
- [x] When a field is disabled or in readonly mode, the text should be light gray not black 

**Round & Application Period tab**

- [x] When a field is disabled, the border has a gap in the bottom left corner 
- [x] When disabled, the text in the Application Start Date box should be light gray, like the Application End Date & Round Start date boxes 

Screen Shot 2023-06-02 at 11 16 56 AM

**Funding Settings tab**

- [x] The header for payout token is cutoff if the selection is ETH 
Screen Shot 2023-06-02 at 11 25 43 AM

- [x] The "USD" header text should be light gray not black (make is the same as the ETH/DAI and % text color of the above headers) 
Screen Shot 2023-06-02 at 11 26 52 AM

- [x] (TBD) Remove redundant "required" labels for YES/NO questions 

**Details**
Say more

### PR DESCRIPTION
**Pull request by vacekj**
## PR checklist

For every PR, make sure that these statements are true:
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't contain type casts and non-null assertions.
- [x] Doesn't add `@ts-ignore`.
- [x] Doesn't disable lints.
- [x] Doesn't use `useState` just for computation - use plain variables instead.
- [x] Splits components into pure components that don't depend on external state or hooks.
- [x] Avoid embedding components within other components
- [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
- [x] Doesn't duplicate existing code.
- [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
- [x] Doesn't contain commented out code.
- [x] Doesn't contain skipped or empty tests.
- [x] If this PR adds/updates any feature, it adds/updates its test script

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Refers/Fixes

fixes #1915

### CODE REVIEW

File: packages/round-manager/src/features/round/ViewRoundSettings.tsx [hunk 1]
```diff
@@ -1825,14 +1825,15 @@ function Funding(props: {
...
 
           <div
-            className={`leading-8 font-normal ${
+            className={`leading-8 flex font-normal ${
               !props.editMode.canEdit ||
               (props.editMode.canEditOnlyRoundEndDate && "text-grey-400")
             }`}
           >
             <input
+              size={matchingFundPayoutToken.name.length ?? 3}
```
Comment (bard) [inline packages/round-manager/src/features/round/ViewRoundSettings.tsx:1834]: If I'm understanding this correctly, and name is a string, then length will never be null or undefined, and the `?? 3` branch will never trigger.

**Review by bard — APPROVED** [review]

**Review by bhargavaparoksham — APPROVED** [review]

File: packages/round-manager/src/features/round/ViewRoundSettings.tsx (hunk 1 above)
Comment (carlbarrdahl) [reply packages/round-manager/src/features/round/ViewRoundSettings.tsx:1834]: I think if name is empty (`""`) it will default to size 3. What happens to the input field when changing between empty, to one character, to two? Will it jump from size 3 to 1 and then 2?

File: packages/round-manager/src/features/round/ViewRoundSettings.tsx [hunk 2]
```diff
@@ -2238,14 +2234,17 @@ function Funding(props: {
             </span>
           </div>
           <div
-            className={`leading-8 font-normal ${
+            className={`leading-8 flex font-normal ${
               !props.editMode.canEdit ||
               (props.editMode.canEditOnlyRoundEndDate && "text-grey-400")
             }`}
```
Comment (carlbarrdahl) [inline packages/round-manager/src/features/round/ViewRoundSettings.tsx:2240]: This library is great for these instances:
https://github.com/lukeed/clsx

Would look like this:
```tsx
className={clsx(`leading-8 flex font-normal`, {
  ["text-grey-400"]: !props.editMode.canEdit || props.editMode.canEditOnlyRoundEndDate
})
```

File: packages/round-manager/src/features/round/ViewRoundSettings.tsx (hunk 1 above)
Comment (bard) [reply packages/round-manager/src/features/round/ViewRoundSettings.tsx:1834]:
```
$ node
Welcome to Node.js v20.6.1.
Type ".help" for more information.
> "".length ?? 3
0
```

If name is empty, length is zero, which is neither null nor undefined, so the `??  3` branch won't trigger.

File: packages/round-manager/src/features/round/ViewRoundSettings.tsx (hunk 2 above)
Comment (vacekj) [reply packages/round-manager/src/features/round/ViewRoundSettings.tsx:2240]: Indeed, however I would leave this sort of refactoring for the actual refactoring ticket for this page, which is imminent after all the current tickets for this page are implemented.

File: packages/round-manager/src/features/round/ViewRoundSettings.tsx (hunk 1 above)
Comment (vacekj) [reply packages/round-manager/src/features/round/ViewRoundSettings.tsx]: the string will never be empty if the token is found, but the token could theoretically not be found for whatever reason, even though typescript doesn't capture this (because it assumes that .filter() on an array always produces a non-empty array), and therefore will be undefined. I forgot some opt. chaining operators, added in the latest commit.

**Review by melissa-neira — APPROVED** [review]
lgtm!
